### ISSUE TITLE
Add Basic python projects for beginers.

### ISSUE THREAD

**Issue by Aayush-hub** [Aayush-hub/Basic-Python-Projects#1]
Add ideas and solutions of creative python projects for beginers for better understanding of concepts and some developement.

**Comment by Ujjawal179** [comment]
Shall I add some python basic projects mad e by me to it .

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by GSNCodes** [comment]
@Aayush-hub  I can add face detection in images. Could you assign me this issue ?

**Comment by ghost** [comment]
Hello please assign it to me. I would like to add Speech to Text

**Comment by JahnaviChitta** [comment]
@Aayush-hub I have done some projects in python, and they will be useful for beginners to look into, and also i can add some basic projects on image detection and recognition. I am interested in contributing for this repo.  Hoping you would assign me this , as this would be a good material for the beginners to go through.

**Comment by cnguyen-uk** [comment]
Happy to contribute some projects to this, but I don't see why I need to star the repo? I can submit a pull request without needing to do this.

**Comment by Aayush-hub** [comment]
@cnguyen-uk buddy I have asked to star this repo, so that i can came to know that this repo is helpul for beginerrs or not.

**Comment by cnguyen-uk** [comment]
@Aayush-hub Understood, however it's likely that people contributing to a repo for beginners are not actually beginners themselves. I won't star this repo since I'm not a beginner, but let me know if you'd like me to contribute to it.
